version: '3.7'

services:
  chessboard:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 runner:app
    volumes:
      - media_volume:/home/app/chessboard/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: autograder_db
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1800:80
    depends_on:
      - chessboard
    volumes:
      - media_volume:/home/app/chessboard/project/media

volumes:
  postgres_data:
  media_volume:

